### ISSUE TITLE
PointNet2_tcl model pred

### ISSUE THREAD

**Issue by xins981** [yzqin/s4g-release#10]
@yzqin hi yuzhe. what means of the movable_logit?

**Comment by yzqin** [comment]
Hi @xins981 ,

The `moveable_logit` is actually something we tried but not used in the S4G paper and the experiments. It repressions the movement direction after grasping the object. However in the experiments we found that as long as our motion planner is strong enough, this information is not so useful. Thus, we do not use it in the S4G experiments.

You can just ignore this prediction.

**Comment by xins981** [comment]
ok, thanks your explanation!
