### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by xinchaosong** [yzqin/s4g-release#3]
Hello, @yzqin,

Is it possible for you to provide more details about how to generate the dataset? I'm trying to look into the code in the data_gen directory but it's really hard to track everything and make it work.

Thank you very much.

**Comment by yzqin** [comment]
Hi @xinchaosong ,

Sorry for the late reply. You can refer to the updated readme for instructions [here](https://github.com/yzqin/s4g-release#data-generation) on data generation.

Thank you!

**Comment by xinchaosong** [comment]
@yzqin No problem. I will take a look. Thank you very much!
