### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by azeaa** [yzqin/s4g-release#4]
Can I generate a data set with my own data? My data is a point cloud file.

**Comment by yzqin** [comment]
You can use your own object models to generate grasp data. That is fairly simple, just replace the filename and file loader to fit your own data. 

But your object model should be a complete mesh or point cloud, the data generation pipeline can not work with partial point cloud, e.g. single view point cloud. It can only deal with single view point cloud during inference time (with the power of neural network) but not data generation time.
