### ISSUE TITLE
Changing model parameters

### ISSUE THREAD

**Issue by kimanton** [yzqin/s4g-release#7]
A question regarding the model. 
In file [curvature model](https://github.com/yzqin/s4g-release/blob/b684ade8fa32ddb55d03a6a36fcfe7f1dc81ca1c/inference/grasp_proposal/configs/curvature_model.yaml#L11), if I want to change model parameters, does that mean I can't use your pretrained weights?

**Comment by yzqin** [comment]
Hi @kimanton,

Yes, if you change the neural network model parameters under [model](https://github.com/yzqin/s4g-release/blob/b684ade8fa32ddb55d03a6a36fcfe7f1dc81ca1c/inference/grasp_proposal/configs/curvature_model.yaml#L10), then the the architecture is changed and you can not use the pre-trained weights. It is the same case for all learning based method and neural networks. 

Sorry that you can not change these parameters if you want to use the pre-trained models. But you can change all the post-processing parameters code that is not related to neural network.

**Comment by kimanton** [comment]
Thank you for explanation
